version: "3.8"

services:
  postgres:
    image: postgres:14
    container_name: postgres_sis
    environment:
      POSTGRES_DB: university
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - ./postgres/scripts/load_data.sh:/docker-entrypoint-initdb.d/load_data.sh
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres/load_data.sql:/home/load_data.sql
      - ./postgres/data:/data
      - postgres_data:/var/lib/postgresql/data
    entrypoint: [ "bash", "-c", "/docker-entrypoint-initdb.d/load_data.sh && docker-entrypoint.sh postgres" ]
    restart: always

  fastapi:
    build: ./fastapi-api
    container_name: fastapi_counseling
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka_server
    environment:
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"

  clickstream:
    build: ./kafka-clickstream
    container_name: clickstream_producer
    depends_on:
      - kafka

  mongodb:
    image: mongo:6
    container_name: mongo_counselors
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: counseling
    volumes:
      - mongodb_data:/data/db
      - ./mongo/init.js:/docker-entrypoint-initdb.d/init.js
      - ./mongo/scripts/load_data.sh:/docker-entrypoint-initdb.d/load_data.sh
      - ./mongo/data:/data
    restart: always

  fastapi_counselor_data:
    build: ./fastapi-counselor-data
    container_name: fastapi_counselor_data
    ports:
      - "8001:8000"
    depends_on:
      - mongodb

volumes:
  postgres_data:
  mongodb_data: