version: "3.8"

services:
  postgres_sis:
    image: postgres:14
    container_name: postgres_sis
    environment:
      POSTGRES_DB: university
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - ./postgres/scripts/load_data.sh:/docker-entrypoint-initdb.d/load_data.sh
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres/load_data.sql:/home/load_data.sql
      - ./postgres/data:/data
      - postgres_data:/var/lib/postgresql/data
    entrypoint: [ "bash", "-c", "/docker-entrypoint-initdb.d/load_data.sh && docker-entrypoint.sh postgres" ]
    restart: always
    networks:
      - data-processing-network

  fastapi:
    build: ./fastapi-api
    container_name: fastapi_counseling
    ports:
      - "8000:8000"
    depends_on:
      - postgres_sis

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    container_name: zookeeper
    ports:
      - "22181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOOKEEPER_CLIENT_PORT=2181
    networks:
      - data-processing-network
  
  kafka:
    image: confluentinc/cp-kafka:7.4.4
    container_name: kafka_server
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "29092:29092"
    depends_on:
      - zookeeper
    networks:
      - data-processing-network

  meeting-request-generator:
    build: ./meeting-request-generator
    container_name: meeting-request-generator
    depends_on:
      - zookeeper
      - kafka
      - postgres_sis
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - KAFKA_SERVER=kafka:9092
      - KAFKA_TOPIC=counselor-requests
    networks:
      - data-processing-network

  clickstream:
    build: ./kafka-clickstream
    container_name: clickstream_producer
    depends_on:
      - kafka

  mongodb:
    image: mongo:6
    container_name: mongo_counselors
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: counseling
    volumes:
      - mongodb_data:/data/db
      - ./mongo/init.js:/docker-entrypoint-initdb.d/init.js
      - ./mongo/scripts/load_data.sh:/docker-entrypoint-initdb.d/load_data.sh
      - ./mongo/data:/data
    restart: always
    networks:
      - data-processing-network

  fastapi_counselor_data:
    build: ./fastapi-counselor-data
    container_name: fastapi_counselor_data
    ports:
      - "8002:8000"
    depends_on:
      - mongodb
    networks:
      - data-processing-network

volumes:
  postgres_data:
  mongodb_data:

networks:
  data-processing-network:
    external: true