version: '3'

services:
  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    hostname: spark-master
    environment:
      - INIT_DAEMON_STEP=setup_spark
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      - spark-network
    volumes:
      - ./data:/data

  jupyter:
    build: .
    container_name: jupyter-delta
    ports:
      - "8888:8888"
    networks:
      - spark-network
    volumes:
      - ./local_lake:/home/jovyan/work
      - ./notebooks:/home/jovyan/
    depends_on:
      - spark-master
    command: "start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''"

networks:
  spark-network:
volumes:
  myvol: